---
kind: ConfigMap
apiVersion: v1
metadata:
  name: auth-config
  namespace: dummy-crm-namespace
data:
  #AUTH_ACCESSTOKEN_URL: https://erp.mydomain.com/oauth/accessToken
  AUTH_ACCESSTOKEN_URL: http://dummy-corp-auth-rust-app.dummy-corp-erp-namespace:8080/accessToken
  AUTH_PROFILE_URL: http://dummy-corp-auth-rust-app.dummy-corp-erp-namespace:8080/profile
  CLIENT_ID: CRM
  REDIRECT_URI: https://crm.mydomain.com/authback/?code=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-crm-rust-app
  namespace: dummy-crm-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-crm-rust-app
  template:
    metadata:
      labels:
        app: dummy-crm-rust-app
    spec:
      containers:
      - name: dummy-crm-rust-app
        image: localhost:32000/dummy-crm-rust-app:latest  # Usar la imagen de tu registro local
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: auth-config  # Referencia al ConfigMap        
        - configMapRef:
            name: postgres-config  # Referencia al ConfigMap        
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 32Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080  